crawler:
  type: 'music' # anime, book, music, game, real
  start: 1 # start page
  end: 1 # end page
  user-agent: 'murlors/bangumi-analysis-coursework (https://github.com/murlors/Bangumi-Analysis-Coursework)'

data:
  path: 'data' # data path

figure:
  path: 'figure'
  rcParams: 
    font.family: 'SimHei'
    savefig.dpi: 300
    figure.figsize: [12, 8]