crawler:
  type: 'music' # anime, book, music, game, real
  start: 1 # start page
  end: 50 # end page
  user-agent: 'murlors/bangumi-analysis-coursework (https://github.com/murlors/Bangumi-Analysis-Coursework)'
  access-token: # insert your access token here

data:
  path: 'data' # data path

figure:
  path: 'figures'
  rcParams: 
    font.family: 'Microsoft YaHei' # 中文字体
    savefig.dpi: 300 # 图片分辨率
    figure.figsize: [12, 8] # 图片大小
    figure.autolayout: True # 自动调整布局